language: node_js
node_js:
  - 12
  - 14.8.0

notifications:
    email: false

install:
  - npm install
  - cd frontend && npm i

script:
  - npm test

deploy:
  provider: heroku
  app: teamseer-upskillingapp
  api_key:
    secure: kcqkSBmG3yoFN/X2FYJenTo6WbVQkq8ggIqtxOJLBUMs6HFKhq6n6dbYwg5MD+0wDTMv7jLUt5WNtef4NOoTk7DxSm2MlH3vee8do1muEbE5uuvN48/gqAK4wEALUbCCpul5mt+ERQFCllWV7GiTrCtE68m8NfqtM7YHUkvSRCC4DAmUWdfAVBhbpaeZzCQewEW59QrGHKMqJ1Tu2uYBlGBbhChKnxEYGo2nulfvG0i5GdV1fZvMrmj3H0EHAC977FgzUde35cf9wLw8Qlnui/zhX/4Z/CTbX9pJcxHb1pw/9Dsa7F1cnV2HihmJIJ/vwNEoXCvV87H2+cInGL7Q+Fr5tkUAAhkDi94/KtDUeEHWQYk3XM7NbVEC3BuRuwW+VCJYxJBAMCwBsEKm/SzfDhVHkGmTHM/sLoPLkvb7HZDNcOs5xXGnKweHXVU4jNEfu+2wVidSX8d3mlmVAMOQ66TyQwZsbHRosF3kxpQ9gAFfplcSfLL4q/gY3HRcNmkNZE3Qj2KWx6mmjFJSEFeP7/mCGk5dffzRmjinf/YBEUlGJ6kcZDLIRjuxHr6LccGe6J/2n+mmxeHZ9hauzRVnP11ZgyUqYKFxKeHlxVZ/SFdpmnOl3V/sfstXe0vQ4+RjX13HX/KGs0XxeHVhTPFS/mgaiPVIrQ/fBPvXmUGJTUc=