language: node_js
node_js:
  - 12
  - 14.8.0

notifications:
    email: false

install:
  - npm install
  - cd frontend && npm i

script:
  - npm test

deploy:
  provider: heroku
  app: teamseer-upskillingapp
  api_key:
    secure: IL6pfd4o7tlPz7PS8pfYn5Z79SyABEmOjJfPfNyOdFdhXgeZv4FOk3QYgB7Ozhgh130stzolDAf6hcU4SPEu+XPpweefgXIOp4MVGcRYRH3EaCbLCEtiZCHp7uRCPJqnCOWFvWOoeCW57uiHcWeW8PcC0hoEvZ7TpU3L0lXOmVkCBYQZ1tyrOdVxO3P0NNw04bkU5NKKvGe/U+YZJroMhfZV6NELBp824iXQBzSeRn18ngbMz1WPnW/w6es7JJSYzMzI/RAIez933tobl7qPoYy3RV7RpfzRRF2ujl/HNp/HX34QIGpjtl4/f/CSGD7jlY6KxEOxuumH0WZWqAZoS0+WyPbbZ7xuiMSRl+p2EUw7Xm9AFpTkGrotaOcilKNGfx7gyMbDqdRMKGcaD1RvrD6tuDzh6CJMd3F/C0bW9FNny5C3JnESY9IAkNpg615/+MnsLiUWox0hxcMW4wiBhrgngr92dJLbGeB2KO3nsBUZMzPLpwCHATAgNUKFjMt0BUbNnnYwn6CZQepNV7p+pJdzto3DK/nT+7X58cKh7cgC3lpmLOBThTl7Bg6ITqREMFAJ2opwp1+RfrAoIJEkv5H9LrNzDEx2eOs+RmHjOTnZN6VmyMfYpLb0SReLNBWNB2p0PYsgoiGJKGHcD7kI1uRZPzkYMGOqVJDg3Um0smI=