language: node_js
node_js:
  - 14.8.0
notifications:
  email: false
install:
  - npm install
  - cd frontend && npm i

script:
  - npm test

before_deploy:
  - cd .. && npm run build

deploy:
  provider: heroku
  app: seer-system
  on:
    repo: BroYash/SEER-System
    branch: master
